In [12]:
from PIL import Image
from src.circle_detection import detect_circles

image = Image.open('./data/test_images/image.png')
result = detect_circles(image, (10,100))

# result.save('./data/results/result.png')

[]


In [1]:
import cv2
import numpy as np

def detect_coins(image_path):
    # 读取图像
    img = cv2.imread(image_path)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    # # 高斯模糊
    blurred = cv2.GaussianBlur(gray, (9, 9), 2)

    # Canny边缘检测
    edges = cv2.Canny(blurred, 50, 150)
    # 显示边缘检测的结果
    cv2.imshow('Edges', edges)

    # 等待按键事件，然后关闭窗口
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    # 霍夫圆变换圆检测
    circles = cv2.HoughCircles(edges, cv2.HOUGH_GRADIENT, 1, minDist=20,
                               param1=50, param2=30, minRadius=10, maxRadius=100)
    
    print(circles)
    if circles is not None:
        circles = np.uint16(np.around(circles))
        for i in circles[0, :]:
            center = (i[0], i[1])  # 圆心(x, y)
            radius = i[2]  # 半径
            cv2.circle(img, center, radius, (255, 0, 0), 2)
            cv2.circle(img, center, 2, (0, 255, 0), 3)
    
    cv2.imshow('Detected Coins', img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

# 使用示例
image_path = './data/test_images/image.png'
detect_coins(image_path)


2024-03-25 16:23:44.574 Python[23024:9482177] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.


[[[ 45.5 258.5  27.8]
  [270.5 118.5  24.6]
  [299.5 264.5  25.7]
  [101.5 195.5  21.1]
  [153.5 197.5  20. ]
  [215.5  50.5  23. ]
  [ 44.5 196.5  18.8]
  [337.5 124.5  19.4]
  [173.5 261.5  26.8]
  [154.5  50.5  23.2]
  [115.5 265.5  21. ]
  [ 45.5 124.5  20.2]
  [213.5 193.5  24. ]
  [276.5  52.5  19.5]
  [271.5 192.5  21.6]
  [357.5 267.5  20.8]
  [206.5 123.5  20.1]
  [103.5 125.5  19.1]
  [100.5  55.5  18.8]
  [152.5 126.5  19.3]
  [242.5 264.5  23. ]
  [337.5  45.5  27.9]
  [352.5 188.5  27.8]]]


: 